name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-os: [ 'windows', 'darwin', 'linux' ]
        go-arch: [ 'amd64', 'arm64' ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: wangyoucao577/go-release-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          goos: ${{ matrix.go-os }}
          goarch: ${{ matrix.go-arch }}
          md5sum: false
          goversion: "1.23"
